[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set1"
name = "set1_customer_pipeline"
description = "Transform customer data from sample set 1 for customers table"
transformer_pipeline = "set1_customer_transformer"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_data/set1/customer_address_set1.csv"
schema_file = "set1_customer_address_input"
label = "Customer address file"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_data/set1/customer_details_set1.csv"
schema_file = "set1_customer_details_input"
label = "Customer details file"

[output]
schema_file = "customer_model"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "customers"
db = "PurchasesDB"
data_label = "Set1"