[[extract_files]]
folder = "/Users/ab/Projects/data-loader/samples/dataset1/"
file_name = "purchases_set1.csv"
schema_name = "set1_purchases_input"
label = "Purchases file"

[details]
name = "set2_purchases_pipeline"
description = "Transform purchase data from sample set 1 for purchases table"
transformer_pipeline = "set1_purchases_transformer"

[output_table]
table_name = "purchases"
schema_name = "purchases_model"
db = "Purchases"
data_label = "Set1"