[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set1"
name = "set1_purchases_pipeline"
description = "Transform purchases data from sample set 1 for purchases table"
transformer_pipeline = "set1_purchases_transformer"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_data/set1/purchases_set1.csv"
schema_file = "set1_purchases_input"
label = "Purchases file"

[output]
schema_file = "purchases_model"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "purchases"
db = "PurchasesDB"
data_label = "Set1"