[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set2"
name = "set2_purchases_pipeline"
description = "Transform purchases data from sample set 2 for purchases table"
transformer_pipeline = "set2_purchases_transformer"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_data/set2/purchases_set2.csv"
schema_file = "set2_purchases_input"
label = "Purchases file"

[output]
schema_file = "purchases_model"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "purchases"
db = "PurchasesDB"
data_label = "Set2"