[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set2"
name = "set2_purchases_pipeline"
description = "Transform purchases data from sample set 2 for purchases table"
transformer_pipeline = "/Users/ab/Projects/data-loader/sample_projects/set2/transformers/set2_purchases_transformer.py"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_projects/set2/data/purchases_set2.csv"
schema_file = "/Users/ab/Projects/data-loader/sample_projects/set2/models/set2_purchases_input_model.py"
label = "Purchases file"

[output]
schema_file = "/Users/ab/Projects/data-loader/sample_projects/models/purchases_model.py"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "purchases"
db = "PurchasesDB"
data_label = "set2"