[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set1"
name = "set1_purchases_pipeline"
description = "Transform purchases data from sample set 1 for purchases table"
transformer_pipeline = "/Users/ab/Projects/data-loader/sample_projects/set1/transformers/set1_purchases_transformer"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_projects/set1/data/purchases_set1.csv"
schema_file = "/Users/ab/Projects/data-loader/sample_projects/set1/models/set1_purchases_input_model"
label = "Purchases file"

[output]
schema_file = "/Users/ab/Projects/data-loader/sample_projects/models/purchases_model"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "purchases"
db = "PurchasesDB"
data_label = "Set1"