[details]
project_path = "/Users/ab/Projects/data-loader/sample_projects/set1"
name = "set1_customer_pipeline"
description = "Transform customer data from sample set 1 for customers table"
transformer_pipeline = "/Users/ab/Projects/data-loader/sample_projects/set1/transformers/set1_customer_transformer"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_projects/set1/data/customer_address_set1.csv"
schema_file = "/Users/ab/Projects/data-loader/sample_projects/set1/models/set1_customer_address_input_model"
label = "Customer address file"

[[extract_files]]
data_file = "/Users/ab/Projects/data-loader/sample_projects/set1/data/customer_details_set1.csv"
schema_file = "/Users/ab/Projects/data-loader/sample_projects/set1/models/set1_customer_details_input_model"
label = "Customer details file"

[output]
schema_file = "/Users/ab/Projects/data-loader/sample_projects/models/customer_model"
output_path = "/Users/ab/Projects/data-loader/sample_output/"
table_name = "customers"
db = "PurchasesDB"
data_label = "Set1"